"""
tests/scenarios/level2_medium.py
Level 2 — Medium: Template-level pipeline requests

Each scenario tests multi-step pipelines that typically map to a known template.
Conversations are 3–5 turns with the user providing biological context.

Complexity: MEDIUM
  - User describes a biological scenario requiring 2–3 tools
  - Usually maps to an existing template in the catalog
  - Requires understanding of organism + sequencing platform
  - Expected: system selects appropriate template and builds pipeline
"""

import os

LEVEL2_SCENARIOS = [
    {
        "id": "L2_01_covid_mapping_lineage",
        "level": 2,
        "difficulty": "medium",
        "description": "SARS-CoV-2 mapping and Pangolin lineage assignment",
        "chat_messages": [
            "I have SARS-CoV-2 samples from a hospital outbreak and need to do mapping and lineage assignment with Pangolin.",
            "Yes, I have paired-end Illumina data. The reads are already trimmed with fastp by our core facility.",
            "That sounds right. I approve the plan, please build the pipeline.",
        ],
        "expect_approved": True,
        "expect_code": True,
        "expect_in_context": ["module_covid_emergency", "step_4TY_lineage__pangolin"],
        "template_ids": ["module_covid_emergency"],
        "component_ids": ["step_2AS_mapping__ivar", "step_4TY_lineage__pangolin"],
        "expect_strategy": "EXACT_MATCH",
        "expect_template_id": "module_covid_emergency",
        "design_plan": "Execute the COVID emergency pipeline. Step 1: Map reads against Wuhan-Hu-1 with iVar for consensus calling. Step 2: Run Pangolin for SARS-CoV-2 lineage classification.",
        "selected_module_ids": ["step_2AS_mapping__ivar", "step_4TY_lineage__pangolin"],
    },
    {
        "id": "L2_02_denovo_host_depletion",
        "level": 2,
        "difficulty": "medium",
        "description": "De novo assembly with host depletion using Bowtie2 + SPAdes",
        "chat_messages": [
            "I want to do de novo assembly on clinical samples, but first I need to remove the host reads. The samples are from bovine respiratory tissue.",
            "Yes, I have the Bos taurus reference genome. I'm using Illumina paired-end data.",
            "Perfect, I approve. Build it.",
        ],
        "expect_approved": True,
        "expect_code": True,
        "expect_in_context": ["module_denovo", "step_2AS_mapping__bowtie"],
        "template_ids": ["module_denovo"],
        "component_ids": ["step_2AS_mapping__bowtie", "step_2AS_denovo__spades"],
        "expect_strategy": "EXACT_MATCH",
        "expect_template_id": "module_denovo",
        "design_plan": "Execute the de novo assembly pipeline with host depletion. Step 1: Deplete host reads with Bowtie2. Step 2: Assemble remaining reads with SPAdes.",
        "selected_module_ids": ["step_2AS_mapping__bowtie", "step_2AS_denovo__spades"],
    },
    {
        "id": "L2_03_westnile_lineage",
        "level": 2,
        "difficulty": "medium",
        "description": "West Nile Virus lineage detection and reference mapping",
        "chat_messages": [
            "I have West Nile Virus samples from dead corvids in the Abruzzo region. I need to determine the lineage and then do consensus mapping.",
            "Yes, I have paired-end Illumina reads from brain tissue. The reads are already trimmed.",
            "That's exactly what I need. I approve, please build it.",
        ],
        "expect_approved": True,
        "expect_code": True,
        "expect_in_context": ["module_westnile", "step_4TY_lineage__westnile"],
        "template_ids": ["module_westnile"],
        "component_ids": ["step_4TY_lineage__westnile"],
        "expect_strategy": "EXACT_MATCH",
        "expect_template_id": "module_westnile",
        "design_plan": "Execute the standard WNV surveillance pipeline. Step 1: Detect WNV lineage from raw reads using the westnile lineage tool. Step 2: Dynamically select the correct reference genome. Step 3: Perform consensus mapping with iVar.",
        "selected_module_ids": ["step_4TY_lineage__westnile"],
    },
    {
        "id": "L2_04_bowtie2_mapping",
        "level": 2,
        "difficulty": "medium",
        "description": "Map reads to a reference genome using Bowtie2",
        "chat_messages": [
            "I want to map my trimmed Illumina reads to a reference genome using Bowtie2. I have the reference FASTA ready.",
            "Yes, that's correct. I approve, build the pipeline.",
        ],
        "expect_approved": True,
        "expect_code": True,
        "expect_in_context": ["step_2AS_mapping__bowtie"],
        "template_ids": [],
        "component_ids": ["step_2AS_mapping__bowtie"],
        "expect_strategy": "CUSTOM_BUILD",
        "expect_template_id": None,
        "design_plan": "Execute a custom pipeline. Step 1: Map trimmed Illumina reads to a reference genome using Bowtie2.",
        "selected_module_ids": ["step_2AS_mapping__bowtie"],
    },
    {
        "id": "L2_05_kmerfinder_species",
        "level": 2,
        "difficulty": "medium",
        "description": "Species identification with KmerFinder on assemblies",
        "chat_messages": [
            "I have assembled bacterial genomes and want to do species identification using KmerFinder.",
            "Yes, the assemblies are from Shovill. I want to confirm the species before running downstream analysis.",
            "I approve. Build it.",
        ],
        "expect_approved": True,
        "expect_code": True,
        "expect_in_context": ["step_3TX_species__kmerfinder"],
        "template_ids": [],
        "component_ids": ["step_3TX_species__kmerfinder"],
        "expect_strategy": "CUSTOM_BUILD",
        "expect_template_id": None,
        "design_plan": "Execute a custom pipeline. Step 1: Species identification using KmerFinder on assembled genomes.",
        "selected_module_ids": ["step_3TX_species__kmerfinder"],
    },
    {
        "id": "L2_RECREATION_REV_01_denovo_spades_to_shovill",
        "level": 2,
        "difficulty": "medium",
        "description": "Revision: host depletion + Shovill assembly",
        "chat_messages": [
            "I want to remove host dna from my illumina reads. Then I need to assemble the rest into contigs.",
            "Approved.",
            "I want to use shovill for the assembly instead of spades.",
        ],
        "expect_approved": True,
        "expect_code": True,
        "expect_in_context": ["module_denovo", "step_1PP_hostdepl__bowtie", "step_2AS_denovo__shovill"],
        "template_ids": ["module_denovo"],
        "component_ids": ["step_1PP_hostdepl__bowtie", "step_2AS_denovo__shovill"],
        "expect_strategy": "CUSTOM_BUILD",
        "expect_template_id": None,
        "design_plan": "Execute revised de novo workflow. Step 1: Host depletion with Bowtie. Step 2: De novo assembly with Shovill.",
        "selected_module_ids": ["step_1PP_hostdepl__bowtie", "step_2AS_denovo__shovill"],
    },
    {
        "id": "L2_RECREATION_REV_02_covid_add_fastqc",
        "level": 2,
        "difficulty": "medium",
        "description": "Revision: add FastQC before iVar + Pangolin",
        "chat_messages": [
            "I have sars cov 2 samples. I want to map them and get the lineage.",
            "Approved.",
            "Can you add a step to check the read quality first. Let us use fastqc for the raw reads.",
        ],
        "expect_approved": True,
        "expect_code": True,
        "expect_in_context": ["module_covid_emergency", "step_0SQ_rawreads__fastq", "step_2AS_mapping__ivar", "step_4TY_lineage__pangolin"],
        "template_ids": ["module_covid_emergency"],
        "component_ids": ["step_0SQ_rawreads__fastq", "step_2AS_mapping__ivar", "step_4TY_lineage__pangolin"],
        "expect_strategy": "CUSTOM_BUILD",
        "expect_template_id": None,
        "design_plan": "Execute revised SARS-CoV-2 workflow. Step 1: Raw read QC with FastQC. Step 2: Consensus mapping with iVar. Step 3: Lineage assignment with Pangolin.",
        "selected_module_ids": ["step_0SQ_rawreads__fastq", "step_2AS_mapping__ivar", "step_4TY_lineage__pangolin"],
    },
    {
        "id": "L2_RECREATION_REV_03_reads_processing_fastp_to_chopper",
        "level": 2,
        "difficulty": "medium",
        "description": "Revision: reads processing with Nanopore trimming",
        "chat_messages": [
            "I have raw illumina reads. I want to check their quality and trim them.",
            "Approved.",
            "I made a mistake. My reads are nanopore. Please use chopper for trimming instead of fastp.",
        ],
        "expect_approved": True,
        "expect_code": True,
        "expect_in_context": ["module_reads_processing", "step_0SQ_rawreads__fastq", "step_1PP_trimming__chopper", "step_3TX_class__kraken"],
        "template_ids": ["module_reads_processing"],
        "component_ids": ["step_0SQ_rawreads__fastq", "step_1PP_trimming__chopper", "step_3TX_class__kraken"],
        "expect_strategy": "CUSTOM_BUILD",
        "expect_template_id": None,
        "design_plan": "Execute revised reads processing workflow. Step 1: QC on raw reads. Step 2: Trim Nanopore reads with Chopper. Step 3: Classify reads with Kraken.",
        "selected_module_ids": ["step_0SQ_rawreads__fastq", "step_1PP_trimming__chopper", "step_3TX_class__kraken"],
    },
    {
        "id": "L2_RECREATION_REV_04_filtered_denovo_spades_to_shovill",
        "level": 2,
        "difficulty": "medium",
        "description": "Revision: filtered assembly with Shovill",
        "chat_messages": [
            "I want to filter my illumina reads using bowtie. Then I need to assemble them into contigs.",
            "Approved.",
            "I actually want to assemble them with shovill instead of spades.",
        ],
        "expect_approved": True,
        "expect_code": True,
        "expect_in_context": ["module_filtered_denovo", "step_1PP_filtering__bowtie", "step_2AS_denovo__shovill"],
        "template_ids": ["module_filtered_denovo"],
        "component_ids": ["step_1PP_filtering__bowtie", "step_2AS_denovo__shovill"],
        "expect_strategy": "CUSTOM_BUILD",
        "expect_template_id": None,
        "design_plan": "Execute revised filtered assembly workflow. Step 1: Filter reads with Bowtie. Step 2: Assemble filtered reads with Shovill.",
        "selected_module_ids": ["step_1PP_filtering__bowtie", "step_2AS_denovo__shovill"],
    },
    {
        "id": "L2_RECREATION_REV_05_plasmids_add_staramr",
        "level": 2,
        "difficulty": "medium",
        "description": "Revision: plasmid detection plus AMR",
        "chat_messages": [
            "I have an assembly and I want to find the plasmids.",
            "Approved.",
            "Can you also add a step to check amr resistance using staramr.",
        ],
        "expect_approved": True,
        "expect_code": True,
        "expect_in_context": ["module_plasmids", "step_4TY_plasmid__mobsuite", "step_4AN_AMR__staramr"],
        "template_ids": ["module_plasmids"],
        "component_ids": ["step_4TY_plasmid__mobsuite", "step_4AN_AMR__staramr"],
        "expect_strategy": "CUSTOM_BUILD",
        "expect_template_id": None,
        "design_plan": "Execute revised plasmid workflow. Step 1: Detect plasmids with MOB-suite. Step 2: Run AMR detection with StarAMR.",
        "selected_module_ids": ["step_4TY_plasmid__mobsuite", "step_4AN_AMR__staramr"],
    },
    {
        "id": "L2_RECREATION_REV_06_scaffolds_vdabricate_to_kmerfinder",
        "level": 2,
        "difficulty": "medium",
        "description": "Revision: scaffolds filtering using KmerFinder",
        "chat_messages": [
            "I need to filter my assembly scaffolds. Then I want to identify the species.",
            "Approved.",
            "Can we use kmerfinder instead of vdabricate for the species identification.",
        ],
        "expect_approved": True,
        "expect_code": True,
        "expect_in_context": ["module_scaffolds_filtering", "step_2AS_filtering__seqio", "step_3TX_species__kmerfinder"],
        "template_ids": ["module_scaffolds_filtering"],
        "component_ids": ["step_2AS_filtering__seqio", "step_3TX_species__kmerfinder"],
        "expect_strategy": "CUSTOM_BUILD",
        "expect_template_id": None,
        "design_plan": "Execute revised scaffolds filtering workflow. Step 1: Species ID with KmerFinder. Step 2: Filter scaffolds with SeqIO.",
        "selected_module_ids": ["step_3TX_species__kmerfinder", "step_2AS_filtering__seqio"],
    },
    {
        "id": "L2_RECREATION_REV_07_variant_lineage_bowtie_to_ivar",
        "level": 2,
        "difficulty": "medium",
        "description": "Revision: variant lineage with iVar",
        "chat_messages": [
            "I have some sars cov 2 reads. I want to map them and find the variant lineage.",
            "Approved.",
            "I want to use ivar for mapping instead of bowtie.",
        ],
        "expect_approved": True,
        "expect_code": True,
        "expect_in_context": ["module_variant_lineage", "step_2AS_mapping__ivar", "step_4TY_lineage__pangolin"],
        "template_ids": ["module_variant_lineage"],
        "component_ids": ["step_2AS_mapping__ivar", "step_4TY_lineage__pangolin"],
        "expect_strategy": "CUSTOM_BUILD",
        "expect_template_id": None,
        "design_plan": "Execute revised variant lineage workflow. Step 1: Map and call consensus with iVar. Step 2: Classify lineage with Pangolin.",
        "selected_module_ids": ["step_2AS_mapping__ivar", "step_4TY_lineage__pangolin"],
    },
    {
        "id": "L2_RECREATION_REV_08_westnile_add_fastqc",
        "level": 2,
        "difficulty": "medium",
        "description": "Revision: West Nile workflow with initial QC",
        "chat_messages": [
            "I have west nile virus samples. I want to map the reads and get the lineage.",
            "Approved.",
            "Make sure to check the quality of the reads first using fastqc.",
        ],
        "expect_approved": True,
        "expect_code": True,
        "expect_in_context": ["module_westnile", "step_0SQ_rawreads__fastq", "step_4TY_lineage__westnile"],
        "template_ids": ["module_westnile"],
        "component_ids": ["step_0SQ_rawreads__fastq", "step_4TY_lineage__westnile"],
        "expect_strategy": "CUSTOM_BUILD",
        "expect_template_id": None,
        "design_plan": "Execute revised West Nile workflow. Step 1: QC raw reads with FastQC. Step 2: Identify lineage with westnile tool. Step 3: Continue reference-based mapping.",
        "selected_module_ids": ["step_0SQ_rawreads__fastq", "step_4TY_lineage__westnile"],
    },
    {
        "id": "L2_RECREATION_REV_09_wgs_bacteria_shovill_to_unicycler",
        "level": 2,
        "difficulty": "medium",
        "description": "Revision: WGS bacteria assembly with Unicycler",
        "chat_messages": [
            "I have bacterial sequencing data. I want to assemble the genomes.",
            "Approved.",
            "Please use unicycler to do the assembly instead of shovill.",
        ],
        "expect_approved": True,
        "expect_code": True,
        "expect_in_context": ["module_wgs_bacteria", "step_2AS_denovo__unicycler"],
        "template_ids": ["module_wgs_bacteria"],
        "component_ids": ["step_2AS_denovo__unicycler"],
        "expect_strategy": "CUSTOM_BUILD",
        "expect_template_id": None,
        "design_plan": "Execute revised WGS bacteria workflow. Step 1: Assemble genomes with Unicycler.",
        "selected_module_ids": ["step_2AS_denovo__unicycler"],
    },
    {
        "id": "L2_RECREATION_REV_10_vdraft_light_use_minimap2",
        "level": 2,
        "difficulty": "medium",
        "description": "Revision: vdraft light with Minimap2",
        "chat_messages": [
            "I have nanopore data. I want to remove host reads. Then I want to map the clean reads to a reference.",
            "Approved.",
            "Please use minimap2 for both host removal and mapping.",
        ],
        "expect_approved": True,
        "expect_code": True,
        "expect_in_context": ["module_vdraft_light", "step_1PP_hostdepl__minimap2", "step_2AS_mapping__minimap2"],
        "template_ids": ["module_vdraft_light"],
        "component_ids": ["step_1PP_hostdepl__minimap2", "step_2AS_mapping__minimap2"],
        "expect_strategy": "CUSTOM_BUILD",
        "expect_template_id": None,
        "design_plan": "Execute revised vdraft-light workflow. Step 1: Host depletion with Minimap2. Step 2: Reference mapping with Minimap2.",
        "selected_module_ids": ["step_1PP_hostdepl__minimap2", "step_2AS_mapping__minimap2"],
    },
    {
        "id": "L2_RECREATION_REV_11_wgs_bacteria_invalid_pangolin_revision",
        "level": 2,
        "difficulty": "medium",
        "description": "Revision rejection: Pangolin requested for bacterial workflow",
        "chat_messages": [
            "I have bacterial sequencing data. I want to assemble the genomes.",
            "Approved.",
            "Actually after assembly, use pangolin to classify the bacterial lineage.",
        ],
        "expect_approved": True,
        "expect_code": True,
        "expect_in_context": ["module_wgs_bacteria"],
        "expect_in_context_initial": ["module_wgs_bacteria"],
        "expect_in_context_revision": ["step_4TY_lineage__pangolin", "step_4TY_MLST__mlst", "step_4TY_cgMLST__chewbbaca"],
        "template_ids": ["module_wgs_bacteria"],
        "component_ids": ["step_2AS_denovo__shovill"],
        "expect_strategy": "EXACT_MATCH",
        "expect_template_id": "module_wgs_bacteria",
        "design_plan": "Execute bacterial WGS assembly module.",
        "selected_module_ids": ["step_2AS_denovo__shovill"],
        "expect_rejection_on_revision": True,
        "rejection_reason_revision": (
            "Pangolin is specific to SARS-CoV-2 lineage classification and cannot be used for bacterial lineage typing. "
            "Use MLST or cgMLST for bacterial typing."
        ),
    },
    {
        "id": "L2_RECREATION_REV_12_variant_lineage_invalid_medaka_revision",
        "level": 2,
        "difficulty": "medium",
        "description": "Revision rejection: Medaka requested for Illumina",
        "chat_messages": [
            "I have sars cov 2 samples. I want to map them and get the lineage.",
            "Approved.",
            "Use medaka for mapping these illumina reads.",
        ],
        "expect_approved": True,
        "expect_code": True,
        "expect_in_context": ["module_covid_emergency"],
        "expect_in_context_initial": ["module_covid_emergency"],
        "expect_in_context_revision": ["step_2AS_mapping__medaka", "step_2AS_mapping__bowtie", "step_2AS_mapping__ivar"],
        "template_ids": ["module_covid_emergency"],
        "component_ids": ["step_2AS_mapping__ivar", "step_4TY_lineage__pangolin"],
        "expect_strategy": "EXACT_MATCH",
        "expect_template_id": "module_covid_emergency",
        "design_plan": "Execute COVID emergency pipeline with iVar consensus and Pangolin lineage.",
        "selected_module_ids": ["step_2AS_mapping__ivar", "step_4TY_lineage__pangolin"],
        "expect_rejection_on_revision": True,
        "rejection_reason_revision": (
            "Medaka is a Nanopore polishing/consensus tool and is incompatible with Illumina reads. "
            "Use iVar or Bowtie-based Illumina-compatible mapping workflows."
        ),
    },
]

_LEGACY_LEVEL2_SCENARIOS = LEVEL2_SCENARIOS
NEW_LEVEL2_SCENARIOS = []

OLD_LEVEL2_TEST_IDS = [s["id"] for s in _LEGACY_LEVEL2_SCENARIOS]
NEW_LEVEL2_TEST_IDS = [s["id"] for s in NEW_LEVEL2_SCENARIOS]


def _env_enabled(var_name: str) -> bool:
    return os.getenv(var_name, "").strip().lower() in {"1", "true", "yes", "on"}


if _env_enabled("ONLY_NEW_SCENARIOS"):
    print("[tests] ONLY_NEW_SCENARIOS is enabled: not testing old Level 2 scenarios.")
    LEVEL2_SCENARIOS = NEW_LEVEL2_SCENARIOS
else:
    LEVEL2_SCENARIOS = _LEGACY_LEVEL2_SCENARIOS + NEW_LEVEL2_SCENARIOS
